apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node
  name: node
  namespace: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  strategy: {}
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - image:  shubhamshinde2025/node-app:
        imagePullPolicy: Always
        name: node
        ports:
        - containerPort: 5173
          name: http
          protocol: TCP