apiVersion: v1
kind: Service
metadata:
  labels:
    app: node
  name: node
  namespace: node-app
spec:
  ports:
  - port: 5173
    protocol: TCP
    targetPort: 5173
  selector:
    app: node 
  type: NodePort